name: sereno_clean_architecture_solid
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # sdk: '>=2.19.2 <3.0.0'
  sdk: '>=3.0.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  get_it: ^7.6.0
  dartz: ^0.10.1
  community_material_icon: ^5.9.55
  provider: ^6.0.5
  mocktail: ^0.3.0
  firebase_core: ^2.14.0
  intl: ^0.18.0
  flutter_markdown: ^0.6.15
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  lint: ^2.0.1

flutter:
  assets:
    - assets/images/

  uses-material-design: true