name: sereno_water_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # sdk: '>=2.19.2 <3.0.0'
  sdk: '>=3.0.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  get_it: ^7.6.0
  dartz: ^0.10.1
  community_material_icon: ^5.9.55
  provider: ^6.0.5
  mocktail: ^0.3.0
  intl: ^0.18.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  dart_date: ^1.2.2
  clock: ^1.1.1
  google_nav_bar: ^5.0.6
  awesome_notifications_core: ^0.8.0 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package
  flutter_launcher_icons: ^0.13.1
  restart_app: ^1.2.1
  flutter_background_service: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  lint: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/water_drop_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/images/

  uses-material-design: true