// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbfhBHA1ii-JAUqjxKz-LlycpxrtQegpM',
    appId: '1:83191235630:web:5240efdf10d1250eaa4bbf',
    messagingSenderId: '83191235630',
    projectId: 'sereno-144e7',
    authDomain: 'sereno-144e7.firebaseapp.com',
    storageBucket: 'sereno-144e7.appspot.com',
    measurementId: 'G-Y5KYBEPBF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGmH3beOV0gAkzpymSGBIcODxOG854PA',
    appId: '1:83191235630:android:98080cf4e21593e5aa4bbf',
    messagingSenderId: '83191235630',
    projectId: 'sereno-144e7',
    storageBucket: 'sereno-144e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVP-fHCS-AHcaqRABdxDjwgWrVpJgjZc',
    appId: '1:83191235630:ios:c76b1be63feccffeaa4bbf',
    messagingSenderId: '83191235630',
    projectId: 'sereno-144e7',
    storageBucket: 'sereno-144e7.appspot.com',
    iosClientId: '83191235630-9amuquptlldshj6niu66u91uop4lse15.apps.googleusercontent.com',
    iosBundleId: 'com.example.serenoCleanArchitectureSolid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVP-fHCS-AHcaqRABdxDjwgWrVpJgjZc',
    appId: '1:83191235630:ios:c76b1be63feccffeaa4bbf',
    messagingSenderId: '83191235630',
    projectId: 'sereno-144e7',
    storageBucket: 'sereno-144e7.appspot.com',
    iosClientId: '83191235630-9amuquptlldshj6niu66u91uop4lse15.apps.googleusercontent.com',
    iosBundleId: 'com.example.serenoCleanArchitectureSolid',
  );
}
